### ISSUE TITLE
Feature: Logger setup

### ISSUE THREAD

**Issue by utkarsh-var** [devfolioco/starter#4]
@ajayns Please setup logging functionality. Search for open source logging lib or packages and install it.

**Comment by apollonian** [comment]
@ajayns It is worth looking into https://github.com/evgenyrodionov/redux-logger since we use Redux.

**Comment by ajayns** [comment]
Looks good @apollonian11 , but that's for logging redux actions that are dispatched yes? I'm unsure what exactly @utkarsh-var mentioned by logging on the client-side. We're currently just logging client-side errors on the console.

**Comment by utkarsh-var** [comment]
We have to setup logger according to the application run environment.
For **dev**, **staging** and **testing** environment we should log the error to the **console** with appropriate error severity levels as mentioned [here](https://en.wikipedia.org/wiki/Syslog).
For the **production** environment, we should not log to console instead we should transport it to central logging servers. @ajayns @apollonian11

**Comment by ajayns** [comment]
@apollonian11 Could we setup some sort of basic config for Sentry or so? That's what's required here yeah?

**Comment by apollonian** [comment]
@ajayns From Devfolio point of view, I think adding Sentry would be cool since we use it internally. Otherwise, I believe it is at the sole discretion of the developer, since this is a starter and not a full-fledged boilerplate.

Adding it right now would also mean configuring the API flow, and putting errorHandlers in place for catching them. It's better to add a React Error Boundary before tackling any of that.

P.S. Check this out! https://reactjs.org/docs/error-boundaries.html

**Comment by ajayns** [comment]
If we're thinking that way, I think logging we could leave it to the dev who's building over this starter. But yes, maybe the React Error Boundary could be good enough for us here, I'll check that out and work on adding it.

**Comment by apollonian** [comment]
Yeah, we can have a separate branch which has Sentry integrated later as well.
